version: '3'

services:
  web:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    command: uvicorn app:app --host 0.0.0.0 --port 8080 # app.py is the entrypoint of the FastAPI application
